In [45]:
# %load data_parser.py
import os
import json
import numpy as np


def get_data(file_dir):
    """
    Will read JSON files from the provided file directory and subdirectories and return a list of dicts
    :param file_dir: directory where to look for input JSON files
    :return: list of dicts converted from JSON files
    """
    print('Starting to read JAAD json files!')
    json_list = []

    for dirpath, dirnames, filenames in os.walk(file_dir):
        JAAD_list = [pos_json for pos_json in filenames if pos_json.endswith('.json')]
        for js in JAAD_list:
            with open(os.path.join(dirpath, js)) as json_file:
                json_list.append(json.load(json_file))

    return json_list


def get_data_TCG(file_dir: str) -> (np.ndarray, dict):
    """
    Read in the TCG dataset and its annotation
    :param file_dir: directory where data and annotations from TCG are stored
    :return: Data as np array and annotations as dict
    """
#     tcg_data = np.load(file_dir + 'tcg_data.npy', allow_pickle=True)
    tcg_data = np.load('tcg_data.npy', allow_pickle=True)
#     with open(file_dir + 'tcg.json') as json_file:
    with open('tcg.json') as json_file:
        tcg_json = json.load(json_file)

    return tcg_data, tcg_json


# get_data('../data/JAAD_output_JSON')

# example usage
tcg_d, tcg_j = get_data_TCG('../data/TCG/')
print(len(tcg_d))
print(tcg_j.keys())
print(len(tcg_j['sequences']))
print(tcg_d[0])
print(tcg_d[0].shape)

550
dict_keys(['sequences', 'dataset', 'description', 'version', 'joint_dictionary'])
550
[[[-1.30057383e-01 -2.87529844e+00  3.21951370e+01]
  [ 1.01548117e-01 -8.05008894e-01  5.99461899e+01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  ...
  [ 9.12524309e+00 -1.62379413e+00 -5.10988693e+01]
  [ 8.91745327e+00  1.96904989e-01 -6.25629425e+00]
  [-4.10138145e-02 -1.42855572e+00  1.86052094e+01]]

 [[-1.28102608e-01 -2.87761379e+00  3.21949310e+01]
  [ 1.02079381e-01 -8.08472654e-01  5.99459534e+01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  ...
  [ 9.12010052e+00 -1.62173269e+00 -5.10997581e+01]
  [ 8.91693451e+00  1.96307000e-01 -6.25704956e+00]
  [-3.96665519e-02 -1.42961226e+00  1.86051254e+01]]

 [[-1.27165717e-01 -2.88150805e+00  3.21945801e+01]
  [ 1.02370057e-01 -8.12958233e-01  5.99454956e+01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
  ...
  [ 9.12307961e+00 -1.62498423e+00 -5.10996361e+01]
  [ 8.91685468e+00  1.97516109e-01 -6.25712585e+00]
  [-

In [46]:
tcg_j['sequences'][0]

{'subject_id': 1,
 'junction': 'T',
 'scene_id': 1,
 'scene_agents': [{'id': 1,
   'position': 'right',
   'intention': 'goes straight',
   'queue': 1}],
 'agent_number': 0,
 'annotation': [['inactive', 'normal-pose', 0, 1045],
  ['inactive', 'transition', 1045, 1112],
  ['stop', 'both-static', 1112, 1461],
  ['inactive', 'transition', 1461, 1573],
  ['clear', 'right-static', 1573, 1818],
  ['inactive', 'transition', 1818, 1951],
  ['go', 'both-static', 1951, 2482],
  ['inactive', 'transition', 2482, 2582],
  ['inactive', 'normal-pose', 2582, 3400]],
 'num_frames': 3400}

In [47]:
tcg_d.shape

(550,)

In [48]:
tcg_d[0].shape

(3400, 17, 3)

In [49]:
type(tcg_d[0])

numpy.ndarray

## Turn 3D data to Tensor

In [50]:
import tensorflow as tf

In [51]:
tensor = tf.convert_to_tensor(tcg_d[0])

In [52]:
tensor[0]

<tf.Tensor: shape=(17, 3), dtype=float64, numpy=
array([[-1.30057383e-01, -2.87529844e+00,  3.21951370e+01],
       [ 1.01548117e-01, -8.05008894e-01,  5.99461899e+01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.81141930e+01, -4.76216803e+00,  4.54645462e+01],
       [-8.32693640e+00, -4.60900272e+00, -9.34862118e+01],
       [-2.61315791e+01, -2.94570554e+00,  1.94638367e+01],
       [-2.66918998e+01,  8.24862693e+00, -4.76636505e+00],
       [-8.61236087e+00, -1.67471149e+00, -5.11175232e+01],
       [-8.90253444e+00,  1.96905289e-01, -6.27750397e+00],
       [-2.72291588e-01, -2.54413196e+00,  4.81910782e+01],
       [ 1.74902343e+01, -5.56502342e+00,  4.61401901e+01],
       [ 9.43912569e+00, -4.90395314e+00, -9.34419808e+01],
       [ 2.44011154e+01, -3.01621366e+00,  1.98845596e+01],
       [ 2.04294420e+01,  1.12028203e+01, -2.35897064e+00],
       [ 9.12524309e+00, -1.62379413e+00, -5.10988693e+01],
       [ 8.91745327e+00,  1.96904989e-01, -6.256294

In [53]:
lst=tcg_j['sequences'][0]['annotation']

In [54]:
# inactive=0
# stop=1
# clear=2
# go=3

#create labels(y)
y_all=[]
for item in lst:
    if item[0]=='inactive':
        y_all.append('0'*(item[3]-item[2]))
    elif item[0]=='stop':
        y_all.append('1'*(item[3]-item[2]))
    elif item[0]=='clear':
        y_all.append('2'*(item[3]-item[2]))
    elif item[0]=='go':
        y_all.append('3'*(item[3]-item[2]))

alle=''
for i in y_all:
    alle+=i

lst_new=[int(char) for char in alle]
label=np.array(lst_new)
label.shape

(3400,)

In [55]:
label[0]

0

## Create data

In [56]:
import pandas as pd

In [57]:
tensor[:,0]

<tf.Tensor: shape=(3400, 3), dtype=float64, numpy=
array([[-0.13005738, -2.87529844, 32.19513702],
       [-0.12810261, -2.87761379, 32.19493103],
       [-0.12716572, -2.88150805, 32.19458008],
       ...,
       [-0.18952513, -3.8057176 , 32.10349274],
       [-0.19430378, -3.80838478, 32.10313416],
       [-0.19790108, -3.81133125, 32.10277557]])>

In [58]:
time = np.arange(0, 3400, 1)
#label
data = pd.DataFrame({'Time': time, 'Label': label})
data
#can't insert 3d tensor,dataframe only accept 1 dimension data

Time  Label
0        0      0
1        1      0
2        2      0
3        3      0
4        4      0
...    ...    ...
3395  3395      0
3396  3396      0
3397  3397      0
3398  3398      0
3399  3399      0

[3400 rows x 2 columns]

## split train and test data

In [59]:
transposed_tensor = tf.transpose(tensor, perm=[1, 0, 2])

In [60]:
reshaped_data = tf.transpose(tensor,perm=[0,2,1])
reshaped_data = tf.reshape(reshaped_data,shape=(-1,3400,17))
reshaped_data

<tf.Tensor: shape=(3, 3400, 17), dtype=float64, numpy=
array([[[-1.30057383e-01,  1.01548117e-01,  0.00000000e+00, ...,
          9.12524309e+00,  8.91745327e+00, -4.10138145e-02],
        [-2.87529844e+00, -8.05008894e-01,  0.00000000e+00, ...,
         -1.62379413e+00,  1.96904989e-01, -1.42855572e+00],
        [ 3.21951370e+01,  5.99461899e+01,  0.00000000e+00, ...,
         -5.10988693e+01, -6.25629425e+00,  1.86052094e+01],
        ...,
        [-1.78855655e+00, -1.85755415e+00,  0.00000000e+00, ...,
          1.61321673e+01,  9.29118534e+00, -1.22030473e+00],
        [ 3.22663345e+01,  6.00353012e+01,  0.00000000e+00, ...,
         -4.97970924e+01, -5.61256409e+00,  1.86197891e+01],
        [ 5.83019354e-01, -1.94702834e+00,  0.00000000e+00, ...,
         -2.90045091e+00,  8.88809128e-01,  8.16196098e-02]],

       [[-1.84105034e+00, -2.02820941e+00,  0.00000000e+00, ...,
          1.60312219e+01,  9.29954963e+00, -1.23943581e+00],
        [ 3.22629776e+01,  6.00355911e+01,  0.00

In [61]:
mean,var=tf.nn.moments(tensor,axes=[0,1,2])
normalized_tensor=(tensor-mean)/tf.sqrt(var)

In [62]:
x_tr=normalized_tensor[:2482]
x_te=normalized_tensor[2482:]
y_tr=label[:2482]
y_te=label[2482:]

In [63]:
x_tr.shape

TensorShape([2482, 17, 3])

### y --> onehot coding

In [64]:
# uniq=np.unique(label)
# sorted_v=np.sort(uniq)
# one_hot=np.zeros((len(label),len(sorted_v)))
# for i,v in enumerate(label):
#     index=np.where(sorted_v==v)[0][0]
#     one_hot[i,index]=1
# # print(one_hot)
# y_tr=one_hot[:2482]
# y_te=one_hot[2482:]

## LSTM 

In [65]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense,Input

# define model
timesteps=2482
features=17
coordinate_values=3
model = Sequential()
# model.add(LSTM(units=32, input_shape=(timesteps, features))) 
model.add(LSTM(64,input_shape=(features, coordinate_values)))
model.add(Dense(1))  # output layer，units is the unit number for output

# compile model
model.compile(optimizer='adam', loss='mean_squared_error',metrics=['accuracy'])

# train model
#x_tr should be (2482，3，17) shape
model.fit(x_tr, y_tr, epochs=10, batch_size=32) 

# prediction
predictions = model.predict(x_te)
# predictions = model.predict(x_te)




Epoch 1/10
78/78 [==============================] - 5s 19ms/step - loss: 0.9116 - accuracy: 0.5580
Epoch 2/10
78/78 [==============================] - 2s 22ms/step - loss: 0.4575 - accuracy: 0.5862
Epoch 3/10
78/78 [==============================] - 2s 22ms/step - loss: 0.4337 - accuracy: 0.5919
Epoch 4/10
78/78 [==============================] - 2s 21ms/step - loss: 0.3886 - accuracy: 0.5943
Epoch 5/10
78/78 [==============================] - 2s 20ms/step - loss: 0.3024 - accuracy: 0.6007
Epoch 6/10
78/78 [==============================] - 2s 20ms/step - loss: 0.2540 - accuracy: 0.6011
Epoch 7/10
78/78 [==============================] - 2s 20ms/step - loss: 0.1853 - accuracy: 0.6056
Epoch 8/10
78/78 [==============================] - 2s 20ms/step - loss: 0.1653 - accuracy: 0.6120
Epoch 9/10
78/78 [==============================] - 2s 20ms/step - loss: 0.1437 - accuracy: 0.6233
Epoch 10/10
78/78 [==============================] - 1s 19ms/step - loss: 0.1324 - accuracy: 0.6370


In [66]:
y_tr,len(y_tr)

(array([0, 0, 0, ..., 3, 3, 3]), 2482)

In [67]:
predictions
# len(predictions)

array([[ 3.6780820e+00],
       [ 3.6953745e+00],
       [ 3.7127151e+00],
       [ 3.7281048e+00],
       [ 3.7435749e+00],
       [ 3.7588410e+00],
       [ 3.7741184e+00],
       [ 3.7888451e+00],
       [ 3.8033497e+00],
       [ 3.8186858e+00],
       [ 3.8347604e+00],
       [ 3.8518033e+00],
       [ 3.8693824e+00],
       [ 3.8862019e+00],
       [ 3.9026208e+00],
       [ 3.9198141e+00],
       [ 3.9378519e+00],
       [ 3.9563630e+00],
       [ 3.9745073e+00],
       [ 3.9923365e+00],
       [ 4.0090261e+00],
       [ 4.0256047e+00],
       [ 4.0423741e+00],
       [ 4.0590668e+00],
       [ 4.0754137e+00],
       [ 4.0916286e+00],
       [ 4.1078048e+00],
       [ 4.1233230e+00],
       [ 4.1388307e+00],
       [ 4.1541166e+00],
       [ 4.1692910e+00],
       [ 4.1837478e+00],
       [ 4.1980853e+00],
       [ 4.2118168e+00],
       [ 4.2251954e+00],
       [ 4.2387772e+00],
       [ 4.2522388e+00],
       [ 4.2650218e+00],
       [ 4.2772574e+00],
       [ 4.2895780e+00],


In [68]:
round_pred=np.round(predictions).astype(int)

In [77]:
# print(round_pred)